//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Out_Door
    {
        public int Id { get; set; }
        public string Outer_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Patient_Id { get; set; }
        public string Docter_Name { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> Docter_fee { get; set; }
        public Nullable<decimal> Reg_fee { get; set; }
        public Nullable<decimal> Other_dorfee { get; set; }
        public string Office { get; set; }
    
        public virtual Tbl_Patient Tbl_Patient { get; set; }
    }
}
