//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Creat_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string User_type { get; set; }
        public bool status { get; set; }
    }
}
