//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Patient()
        {
            this.Out_Door = new HashSet<Out_Door>();
        }
    
        public int Id { get; set; }
        public string Patient_Id { get; set; }
        public string Patient_Name { get; set; }
        public Nullable<System.DateTime> Patient_DOJ { get; set; }
        public Nullable<System.DateTime> Patient_DOB { get; set; }
        public Nullable<decimal> Patient_Age { get; set; }
        public string Patient_Address { get; set; }
        public string Patient_MobileNo { get; set; }
        public string Patient_EmailId { get; set; }
        public string type { get; set; }
        public string sex { get; set; }
        public string Hight { get; set; }
        public string Weight { get; set; }
        public string BP { get; set; }
        public string Care_of { get; set; }
        public string Care_of_Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Out_Door> Out_Door { get; set; }
    }
}
